# Generated by Django 2.2.5 on 2019-09-10 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=10)),
                ('open', models.IntegerField(default=0)),
                ('high', models.IntegerField(default=0)),
                ('low', models.IntegerField(default=0)),
                ('price', models.IntegerField(default=0)),
                ('volume', models.IntegerField(default=0)),
                ('latest_trading_date', models.DateTimeField(verbose_name='latest trading date')),
                ('previous_close', models.IntegerField(default=0)),
                ('change', models.IntegerField(default=0)),
                ('change_percent', models.IntegerField(default=0)),
            ],
        ),
    ]
