# Generated by Django 2.2.5 on 2019-09-29 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quote_endpoint', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Day_to_Day_Volatility',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Equity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equity', models.CharField(max_length=6)),
            ],
            options={
                'db_table': 'equity',
            },
        ),
        migrations.RemoveField(
            model_name='quote',
            name='latest_trading_date',
        ),
    ]
